movie_library/movie_library/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path('accounts/', include('allauth.urls')),
    path('contact/', include('contact.urls')),
    path('', include('movies.urls')),
    path('pages/', include('django.contrib.flatpages.urls')),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movie_library/movies/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.MoviesView.as_view(), name='main'),
    path('filter/', views.FilterMovies.as_view(), name='filter'),
    path('search/', views.Search.as_view(), name='search'),
    path('<slug:slug>/', views.MovieDetailView.as_view(), name='movie_detail'),
    path('<slug:slug>/review/<int:pk>/', views.ReviewView.as_view(), name='review'),
    path('review/<int:pk>/', views.AddReview.as_view(), name='add_review'),
    path('comment/<int:pk>/', views.AddComment.as_view(), name='add_comment'),
    path('actor/<int:pk>/', views.ActorDetailView.as_view(), name='actor_detail')
]

movie_library/movies/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    """Категории"""

    name = models.CharField('Категория', max_length=150)
    description = models.TextField('Описание')
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Actor(models.Model):
    """Актеры и режиссеры"""

    first_name = models.CharField('Имя', max_length=50)
    last_name = models.CharField('Фамилия', max_length=50)
    age = models.PositiveSmallIntegerField('Возраст', null=True, blank=True)
    country = models.CharField('Страна', max_length=50, null=True)
    description = models.TextField('Описание')
    image = models.ImageField('Изображение', upload_to='actors/')

    def __str__(self):
        return f'{self.first_name}  {self.last_name}'

    def get_full_name(self):
        return f'{self.first_name}  {self.last_name}'

    class Meta:
        verbose_name = 'Актеры и режиссеры'
        verbose_name_plural = 'Актеры и режиссеры'


class Genre(models.Model):
    """Жанры"""

    name = models.CharField('Жанр', max_length=25)
    description = models.TextField('Описание')
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Жанр'
        verbose_name_plural = 'Жанры'


class Movie(models.Model):
    """Фильмы"""

    title = models.CharField('Название', max_length=100)
    tagline = models.CharField('Слоган', max_length=100, default='')
    description = models.TextField('Описание')
    poster = models.ImageField('Постер', upload_to='movies/')
    trailer_link = models.URLField('Трейлер', null=True)
    year = models.PositiveSmallIntegerField('Год выхода', null=True, blank=True)
    country = models.CharField('Страна', max_length=50)
    directors = models.ManyToManyField(Actor, verbose_name='Режиссер', related_name='film_director')
    actors = models.ManyToManyField(Actor, verbose_name='Актеры', related_name='film_actor')
    genres = models.ManyToManyField(Genre, verbose_name='Жанры')
    world_premiere = models.DateField('Мировая премьера', null=True, blank=True)
    budget = models.PositiveIntegerField('Бюджет', null=True, blank=True, help_text='Сумма в долларах')
    fees_in_world = models.PositiveIntegerField('Сборы в мире', null=True, blank=True, help_text='Сумма в долларах')
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, verbose_name='Категория', null=True)
    url = models.SlugField(max_length=160, unique=True)
    draft = models.BooleanField('Черновик', default=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('movie_detail', kwargs={'slug': self.url})
        
    class Meta:
        verbose_name = 'Фильм'
        verbose_name_plural = 'Фильмы'


class MovieShots(models.Model):
    """Кадры из фильма"""

    title = models.CharField('Заголовок', max_length=50)
    image = models.ImageField('Изображение', upload_to='movie_shots/')
    movie = models.ForeignKey(
        Movie, on_delete=models.CASCADE, verbose_name='Фильм')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Кадр из фильма'
        verbose_name_plural = 'Кадры из фильма'


class Review(models.Model):
    """Отзывы"""

    email = models.EmailField()
    name = models.CharField('Имя', max_length=50)
    title = models.CharField('Заголовок', max_length=100)
    text = models.TextField('Текст отзыва')
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, verbose_name='Фильм')

    def __str__(self):
        return f'{self.name} - {self.movie}'

    def get_comment(self):
        return self.comment_set.filter(parent__isnull=True)

    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'


class Comment(models.Model):
    """Комментарии"""
    
    author = models.CharField('Автор', max_length=50)
    email = models.EmailField()
    text = models.TextField('Комментарий')
    review = models.ForeignKey(Review, on_delete=models.CASCADE, verbose_name='Комментируемый отзыв')
    parent = models.ForeignKey('self', verbose_name='Родитель', on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return f'Comment by {self.author}'

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

movie_library/movies/forms.py
from django import forms
from snowpenguin.django.recaptcha3.fields import ReCaptchaField

from .models import Review, Comment


class ReviewForm(forms.ModelForm):
    """Форма отзыва"""

    captcha = ReCaptchaField()

    class Meta:
        model = Review
        fields = ('name', 'email', 'text', 'title')
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control border'}),
            'email': forms.EmailInput(attrs={'class': 'form-control border'}),
            'text': forms.Textarea(attrs={'class': 'form-control border'}),
            'title': forms.TextInput(attrs={'class': 'form-control border'}),
            
        }


class CommentForm(forms.ModelForm):
    """Форма добавления комментария к отзыву"""

    class Meta:
        model = Comment
        fields = ('text', 'author', 'email')

movie_library/movies/views.py
from django.shortcuts import redirect
from django.views.generic import ListView, DetailView
from django.views.generic.base import View


from .forms import ReviewForm, CommentForm
from .models import Movie, Actor, Genre, Review


class GenresYears:
    """Жанры и годы выхода фильмов"""

    def get_genres(self):
        return Genre.objects.all()
    
    def get_years(self):
        return Movie.objects.filter(draft=False).values('year').order_by('-year')


class MoviesView(GenresYears, ListView):
    """Вывод фильмов"""

    model = Movie
    queryset = Movie.objects.filter(draft=False)
    paginate_by = 2


class MovieDetailView(GenresYears, DetailView):
    """Детальное описание фильма"""

    model = Movie
    slug_field = 'url'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = ReviewForm()
        return context


class AddReview(View):
    """Добавление отзыва"""

    def post(self, request, pk):
        form = ReviewForm(request.POST)
        movie = Movie.objects.get(id=pk)
        if form.is_valid():
            form = form.save(commit=False)
            form.movie = movie
            form.save()
        return redirect(movie.get_absolute_url())


class ReviewView(DetailView):
    """Просмотр отзыва и комментариев"""

    model = Review
    template_name = 'movies/review.html'
    

class AddComment(View):
    """Добавление комментария"""

    def post(self, request, pk):
        form = CommentForm(request.POST)
        review = Review.objects.get(id=pk)
        print(review)
        if form.is_valid():
            form = form.save(commit=False)
            if request.POST.get('parent', None):
                form.parent_id = int(request.POST.get('parent'))
            form.review = review
            form.save()
        return redirect('review', pk=review.id, slug=review.movie.url)
        

class ActorDetailView(GenresYears, DetailView):
    """Детальное описание актера/режиссера"""

    model = Actor
    template_name = 'movies/actor.html'
    
    def get_context_data(self, **kwargs):
        """Передает с контекстом суммарное количество фильмов с которыми работал актер/режиссер"""
        context = super().get_context_data(**kwargs)
        queryset = Actor.objects.get(pk=context['actor'].id)
        total_movies = queryset.film_actor.count() + queryset.film_director.count()
        context['total_movies'] = total_movies
        return context


class FilterMovies(GenresYears, ListView):
    """Фильтрация фильмов"""

    paginate_by = 2

    def get_queryset(self):
        if "genre" in self.request.GET:
            queryset = Movie.objects.filter(genres__in=self.request.GET.getlist('genre'))
            if "year" in self.request.GET:
                queryset = queryset.filter(year__in=self.request.GET.getlist('year'))
        else:
            queryset = Movie.objects.filter(year__in=self.request.GET.getlist('year'))
        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['year'] = ''.join([f'year={x}&' for x in self.request.GET.getlist('year')])
        context['genre'] = ''.join([f'genre={x}&' for x in self.request.GET.getlist('genre')])
        return context


class Search(ListView):
    """Поиск фильмов по названию"""

    paginate_by = 2

    def get_queryset(self):
        return Movie.objects.filter(title__icontains=self.request.GET.get('q'))
    
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['q'] = f'q={self.request.GET.get("q")}&'
        return context

movie_library/templates/movies/actor.html
{% extends 'movies/base.html' %}

{% load i18n %}

{% block title %}
    {{ Actor.first_name }}{{ Actor.last_name }}
{% endblock %}

{% block container%}
    <div class="container py-md-3">
{% endblock %}

{% block sidebar %}
    <div class="side-bar col-lg-4">
{% endblock %}

{% block movie %}
    <div class="left-ads-display col-lg-8">
        <div class="row">
            <div class="desc1-left col-md-6">
                <img src="{{ actor.image.url }}" class="img-fluid" alt="">
            </div>
            <div class="desc1-right col-md-6 pl-lg-4">
                <h3 class="editContent" style="outline: none; cursor: inherit;">
                    {{ actor.first_name }} {{ actor.last_name }}
                </h3>
                <ul>
                    <li style="list-style: none"><span><b>{% trans 'Возраст' %}: </b>{{ actor.age }} лет</span></li>
                    <li style="list-style: none"><span><b>{% trans 'Страна' %}: </b>{{ actor.country }}</span></li>
                    <li style="list-style: none"><span><b>{% trans 'Всего фильмов' %}: </b>{{ total_movies }}</span></li>
                </ul>
            </div>
            <div class="row sub-para-w3layouts mt-5">
                <h3 class="shop-sing editContent" style="outline: none; cursor: inherit;">
                    {% trans 'Биография' %}
                </h3>
                <p class="editContent" style="outline: none; cursor: inherit;">
                    {{ actor.description }}
                </p>
                <div>
                    <ul>
                        <h5 class="shop-sing editContent">{% trans 'Актер' %}:</h5>
                        {% if actor.film_actor.all %}
                            {% for movie in actor.film_actor.all %}
                                <li><a href="{% url 'movie_detail' movie.url %}">{{ movie.title }}</a> ({{movie.year}})</li>
                            {% endfor %}
                        {% else %}
                            <p>{{ actor.get_full_name }} {% trans 'нигде не снимался' %}...</p>
                        {% endif %}
                        <h5 class="shop-sing editContent">{% trans 'Режиссер' %}:</h5>
                        {% if actor.film_director.all %}
                            {% for movie in actor.film_director.all %}
                                <li><a href="{% url 'movie_detail' movie.url %}">{{ movie.title }}</a> ({{movie.year}})</li>
                            {% endfor %}
                        {% else %}
                            <p>{{ actor.get_full_name }} {% trans 'ничего не режиссировал' %}...</p>
                        {% endif %}
                    </ul>
                </div>
            </div>  
        </div>
    </div>
{% endblock %}

movie_library/templates/movies/base.html
{% extends 'base.html' %}

{% block title %}
{% endblock %}

{% block content %}
    <section class="ab-info-main py-md-5 py-4 editContent" style="padding-left: 3rem; padding-right: 3rem;">
        {% block container%}
            <div class="container-fluid py-md-3">
        {% endblock %}
            <div class="row">
                {% block sidebar%}
                    <div class="side-bar col-lg-3">
                {% endblock %}
                {% include 'include/sidebar.html' %}
                </div>    
                {% block movie %}
                {% endblock %}
            </div>
        </div>
    </section>
{% endblock %}

movie_library/templates/movies/movie_detail.html
{% extends 'movies/base.html' %}

{% load static i18n %}

{% block title %}
    {{ movie.title }}
{% endblock %}

{% block container%}
    <div class="container py-md-3">
{% endblock %}

{% block sidebar %}
    <div class="side-bar col-lg-4">
{% endblock %}

{% block movie %}
    <div class="left-ads-display col-lg-8">
        <div class="row">
            <div class="desc1-left col-md-6">
                <img src="{{ movie.poster.url }}" class="img-fluid" alt="">
            </div>
            <div class="desc1-right col-md-6 pl-lg-4">
                <h3 class="editContent" style="outline: none; cursor: inherit;">
                    {{ movie.title }}
                </h3>
                <ul>
                    <li style="list-style: none"><span><b>{% trans 'Год' %}: </b>{{ movie.year }}</span></li>
                    <li style="list-style: none"><span><b>{% trans 'Страна' %}: </b>{{ movie.country }}</span></li>
                    <li style="list-style: none"><span><b>{% trans 'Слоган' %}: </b>{{ movie.tagline }}</span></li>
                    <li style="list-style: none">
                        <span><b>{% trans 'Режиссер' %}: </b>
                            {% for director in movie.directors.all %}
                                <a href="{% url 'actor_detail' director.id %}">{{ director.get_full_name }}</a>
                            {% endfor %}
                        </span>
                    </li>
                    <li style="list-style: none">
                        <span><b>{% trans 'Жанры' %}: </b>
                            {% for genre in movie.genres.all %}
                                {{ genre.name }}
                            {% endfor %}
                        </span>
                    </li>
                    <li style="list-style: none"><span><b>{% trans 'Премьера в мире' %}: </b>{{ movie.world_premiere }}</span></li>
                    <li style="list-style: none"><span><b>{% trans 'Бюджет' %}: </b>${{ movie.budget }}</span></li>
                    <li style="list-style: none"><span><b>{% trans 'Сборы в мире' %}: </b>${{ movie.fees_in_world }}</span></li>
                </ul>    
            </div>
        </div>
        <div class="row sub-para-w3layouts mt-5">
            <h3 class="shop-sing editContent" style="outline: none; cursor: inherit;">
                {% trans 'О фильмe' %} {{ movie.title }}
            </h3>
            <p>
                {% for image in movie.movieshots_set.all %}
                    <img src="{{ image.image.url }}" class="img-movie-shots" alt="">
                {% endfor %}
            </p>
            <p class="editContent" style="outline: none; cursor: inherit;">{{ movie.description }}</p>
            <div style="width: 100%;">
                <h3 class="shop-sing editContent" style="outline: none; cursor: inherit;">
                    {% trans 'Трейлер к фильму' %}
                </h3>
                <p class="mt-3 italic-blue editContent" style="outline: none; cursor: inherit;">
                    <iframe width="560" height="315" src="{{ movie.trailer_link }}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                </p>
            </div>
            <div>
                <h3 class="shop-sing editContent" style="outline: none; cursor: inherit;">
                    {% trans 'Актеры' %}
                </h3>
                <ul>
                    {% for actor in movie.actors.all %}
                        <li><a href="{% url 'actor_detail' actor.id %}">{{ actor.get_full_name }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="single-form-left">
                <!-- contact form grid -->
                <div class="contact-single">
                    <h3 class="editContent" style="outline: none; cursor: inherit;">
                        {% trans 'Оставить отзыв' %}
                    </h3>
                    <form action="{% url 'add_review' movie.id %}" method="post" class="mt-4">
                        {% csrf_token %}
                        <div class="form-group1"
                                style="outline: none; cursor: inherit;">
                            <label for="contacttitle" class="editContent">
                                {% trans 'Заголовок' %}
                            </label>
                            {{ form.title }}
                        </div>                
                        <div class="form-group editContent"
                                style="outline: none; cursor: inherit;">
                            <label for="contactcomment" class="editContent">
                                {% trans 'Ваш отзыв' %}
                            </label>
                            {{ form.text }}
                        </div>
                        <div class="d-sm-flex">
                            <div class="col-sm-6 form-group p-0 editContent">
                                <label for="contactusername" class="editContent">
                                    {% trans 'Ваше имя' %}
                                </label>
                                {{ form.name }}
                            </div>
                            <div class="col-sm-6 form-group ml-sm-3 editContent">
                                <label for="contactemail" class="editContent">
                                    {% trans 'Ваш Email' %}
                                </label>
                                {{ form.email }}
                            </div>
                            {{ form.captcha }}
                        </div>
                        <button type="submit" class="mt-3 btn btn-success btn-block py-3">
                            {% trans 'Отправить' %}
                        </button>
                    </form>
                </div>
                <!--  //contact form grid ends here -->
            </div>
        </div>
        {% for review in movie.review_set.all %}
            <div class="media py-5">
                <div class="media-body mt-4">
                    <h4 class="mt-0 editContent">
                        {{ review.name }}
                    </h4>
                    <h6 class="mt-1 editContent">
                        {{ review.title }}
                    </h6>
                    <p class="mt-2 editContent">
                        {{ review.text }}
                    </p>
                    {% if user.is_authenticated %}
                        <a href="{% url 'review' pk=review.id slug=review.movie.url %}">{% trans 'Комментировать' %}</a>
                    {% else %}
                        <p style="color: #ff4c4c;">{% trans 'Войдите, чтобы комментировать' %}</p>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

movie_library/templates/movies/movie_list.html
{% extends 'movies/base.html' %}

{% block title %}
{% endblock  %}

{% block header %}bg1{% endblock %}

{% block movie %}
    <div class="left-ads-display col-lg-9">
        <div class="row">
            {% for movie in movie_list %}
                <div class="col-md-4 product-men">
                    <div class="product-shoe-info editContent text-center mt-lg-4" >
                        <div class="men-thumb-item">
                            <img src="{{ movie.poster.url }}" class="img-fluid" alt="" >
                        </div>
                        <div class="item-info-product">
                            <h4 class="">
                                <a href="{{ movie.get_absolute_url }}" class="editContent" >{{ movie.title }}</a>
                            </h4>

                            <div class="product_price">
                                <div class="grid-price">
                                    <span class="money editContent" >{{ movie.tagline }}</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="grid-img-right mt-4 text-right bg bg1" >
            {% include 'include/pagination.html' %}
        </div>
    </div>
{% endblock %}

 

movie_library/templates/movies/review.html
{% extends 'movies/base.html' %}

{% load i18n %}

{% block container%}
    <div class="container py-md-3">
{% endblock %}

{% block content %}
    <section class="ab-info-main py-md-5 py-4 editContent" style="padding-left: 3rem; padding-right: 3rem;">
        <div class="container">
            {% if user.is_authenticated %}
                <div class="row">
                    <div class='review_block'>
                        <h3>
                            {{ review.name }}
                        </h3>
                        <h5>
                            {{review.title}}
                        </h5>
                        <p>{{ review.text }}</p>
                    </div>
                    <div class="comment-form"> 
                        <h5>{% trans 'Ваш комментарий' %}</h5>
                        <form action="{% url 'add_comment' review.id %}" method="post" class="mt-4" id="formComment">
                            {% csrf_token %}
                            <input type="hidden" id='contactparent' name="parent" value="">
                            <div class="form-comment editContent">
                                <textarea class="form-control border" rows="5" name="text" id="contactcomment" required=""></textarea>
                                <button type="submit" class="btn-comment btn-success">
                                    <span class="fa fa-comment-o"></span>
                                </button>
                            </div>
                            <input type="hidden" name="author" value="{{ user.username }}">
                            <input type="hidden" name='email' value="{{ user.email }}">
                        </form>
                    </div>
                </div>
                {% for comment in review.get_comment %}
                    <div class="media py-5">
                        <div class="media-body mt-4">
                            <h4 class="mt-0 editContent">
                                {{ comment.author }}
                            </h4>
                            <p class="mt-2 editContent">
                                {{ comment.text }}
                            </p>
                            <a href="#formComment" onclick="addReview('{{ comment.author }}', '{{ comment.id }}')">{% trans 'Ответить' %}</a>
                            {% for comm in comment.comment_set.all %}
                                <div class="media mt-5 editContent answer">
                                    <div class="media-body">
                                        <h5 class="mt-0 editContent">{{ comm.author }}</h5>
                                        <p class="mt-2 editContent">{{ comm.text }}</p>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <p style="color: #ff4c4c;">{% trans 'Войдите, чтобы комментировать и просматривать комментарии' %}...</p>
            {% endif %}    
        </div>
    </section>
    <script>
        function addReview(name, id) {
            document.getElementById('contactparent').value = id;
            document.getElementById('contactcomment').innerText = `${name}, `

        }
    </script>    
{% endblock %}